#!/bin/bash

# Slackware build script for aichat

# Copyright Martin Bångens Sweden
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# shellcheck disable=SC2034
cd "$(dirname "$0")"; CWD=$(pwd)

PRGNAM=aichat
VERSION=${VERSION:-0.30.0}
GIT_SHA=${GIT_SHA:-430416d914896c3534c04b84c0226910c64e3e66}
GIT_URL="https://github.com/sigoden/aichat.git"
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

# shellcheck disable=SC1091
source helpers/bash_funktions

use_opt_rust

set -e

prepare_git_source "$GIT_URL" "$GIT_SHA"
set_permissions

cargo build --release --all-features

install -vDm755 -t "$PKG/usr/bin" target/release/aichat

install -vDm644 scripts/completions/aichat.bash "$PKG/usr/share/bash-completion/completions/aichat"
install -vDm644 scripts/completions/aichat.fish "$PKG/usr/share/fish/vendor_completions.d/aichat.fish"
install -vDm644 scripts/completions/aichat.nu "$PKG/usr/share/nu/completions/aichat.nu"
install -vDm644 scripts/completions/aichat.ps1 "$PKG/usr/share/powershell/completions/aichat.ps1"
install -vDm644 scripts/completions/aichat.zsh "$PKG/usr/share/zsh/site-functions/_aichat"

install -vDm644 -t "$PKG/usr/share/aichat" scripts/shell-integration/integration.bash
install -vDm644 -t "$PKG/usr/share/aichat" scripts/shell-integration/integration.nu
install -vDm644 -t "$PKG/usr/share/aichat" scripts/shell-integration/integration.zsh
install -vDm644 -t "$PKG/usr/share/aichat" scripts/shell-integration/integration.fish
install -vDm644 -t "$PKG/usr/share/aichat" scripts/shell-integration/integration.ps1

strip_pkg
install_docs LICENSE-MIT README.md

#   |-----handy-ruler------------------------------------------------------|
write_slack_desc "$PKG" "$PRGNAM" \
    "$PRGNAM (LLM CLI tool)" \
    "All-in-one LLM CLI tool featuring Shell Assistant, Chat-REPL, RAG," \
    "AI Tools & Agents, with access to OpenAI, Claude, Gemini, Ollama," \
    "Groq, and more."

cd "$PKG"
/sbin/makepkg -l y -c n "$OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
