#!/bin/bash
if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ -n "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  # shellcheck disable=SC2034
  SLKCFLAGS="-O2"
  # shellcheck disable=SC2034
  LIBDIRSUFFIX=""
fi


prepare_directories () {
  rm -rf "$PKG"
  mkdir -p "$TMP" "$PKG" "$OUTPUT"
}

prepare_git_source () {
  local URL=$1
  local REPO="${URL##*/}"
  local GIT_SHA=$2
  prepare_directories
  cd "$TMP" || exit 1
  rm -rf "$REPO"
  git clone "$URL" || exit 1
  cd "$REPO" || exit 1
  git -c advice.detachedHead=false checkout "$GIT_SHA" || exit 1
}

prepare_tar_source () {
  local URL=$1
  local TAR="${URL##*/}"
  local DIR="${TAR%.tar*}"
  local TAR_SHA256=$2
  prepare_directories
  cd "$TMP" || exit 1
  wget -c "$URL" || exit 1
  if ! echo "${TAR_SHA256}  ${TAR}" | sha256sum -c; then
    echo "sha256sum mismatch"
    exit 1
  fi
  rm -rf "$DIR"
  tar xvf "$TAR"
  cd "$DIR" || exit 1
}

set_permissions () {
  chown -R root:root .
  find -L . \
    \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
    -o -perm 511 \) -exec chmod 755 {} \; -o \
    \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
    -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
}
